### ISSUE TITLE
Auto-Reconnect on API EOF

### ISSUE THREAD

**Issue by sn0w** [sn0w/shiro#42]
The bot should catch this and auto-connect instead of triggering a container reboot.

```
2017/10/25 21:39:30 [DG1] wsapi.go:165:listen() error reading from gateway wss://gateway.discord.gg/?v=6&encoding=json websocket, websocket: close 1006 (abnormal closure): unexpected EOF
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 31172 [running]:
code.lukas.moe/x/shiro/vendor/code.lukas.moe/x/equinox.AdapterPanicHandler()
	/home/travis/gopath/src/code.lukas.moe/x/shiro/vendor/code.lukas.moe/x/equinox/adapter.go:33 +0xe6
panic(0xb54e00, 0x10e6030)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:491 +0x283
code.lukas.moe/x/shiro/vendor/code.lukas.moe/x/equinox.(*Router).Handle(0xc420300300, 0xc4205be000)
	/home/travis/gopath/src/code.lukas.moe/x/shiro/vendor/code.lukas.moe/x/equinox/router.go:98 +0x9df
code.lukas.moe/x/shiro/src/core.OnMessageCreate(0xc42073c900, 0xc42000e470)
	/home/travis/gopath/src/code.lukas.moe/x/shiro/src/core/discord_message.go:30 +0x3a
code.lukas.moe/x/shiro/vendor/github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xca18e8, 0xc42073c900, 0xb558e0, 0xc42000e470)
	/home/travis/gopath/src/code.lukas.moe/x/shiro/vendor/github.com/bwmarrin/discordgo/eventhandlers.go:496 +0x57
created by code.lukas.moe/x/shiro/vendor/github.com/bwmarrin/discordgo.(*Session).handle
	/home/travis/gopath/src/code.lukas.moe/x/shiro/vendor/github.com/bwmarrin/discordgo/event.go:162 +0x114
```

**Comment by sn0w** [comment]
This apparently happens when a lot of messages are sent by the bot.
The problem appeared twice on the same day when some users decided to randomly talk to cleverbot for like 3 hours.
